spring:
  application:
    name: suivia-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:suiviadb}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: validate # Flyway gerencia o banco! Evita quebras no mapeamento.
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true

aws:
  region: sa-east-1
  s3:
    bucket: suivia-invoices-raw
  sqs:
    queue-name: suivia-match-queue

focusnfe:
  base-url: https://api.focusnfe.com.br
  token: ${FOCUS_NFE_TOKEN:mock_token_para_dev}
